title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://airvlab.github.io/guide3d/

aux_links:
  Template Repository: https://airvlab.github.io/guide3d/
